import Footer from "@/components/Footer";
import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "@/components/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hospital Connection",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full`}>
        <Provider>
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
